repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^(tests/|tmp/)
    -   id: end-of-file-fixer
        exclude: ^(tests/|tmp/)
    -   id: check-yaml
        exclude: ^(tests/|tmp/)
    -   id: check-added-large-files
        exclude: ^(tests/|tmp/)
    -   id: debug-statements
        exclude: ^(tests/|tmp/)
    -   id: requirements-txt-fixer
        exclude: ^(tests/|tmp/)

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3.11
        args: [--line-length=120]
        exclude: ^(tests/|tmp/)

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        args: [--line-length=120, --profile=black]
        exclude: ^(tests/|tmp/)

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.0
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
        exclude: ^(tests/|tmp/)

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        args: [--in-place, --wrap-summaries=120, --wrap-descriptions=120]
        exclude: ^(tests/|tmp/)

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--max-line-length=120, --ignore=D400]
        exclude: ^(tests/|tmp/)
