version: '3.8'

services:
  app:
    # build: .
    image: ghcr.io/betterandbetterii/the-lab:latest
    volumes:
      - ./tmp/persist:/app/tmp/persist
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app_network
    restart: always

  db:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_doc_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
